steps:
  # Step 1: Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'function'  # Change this to the actual path of your Node.js project

  # Step 2: Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/your-project-id/your-image-name:latest', '.']
    dir: 'function'  # Change this to the actual path of your Node.js project

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/your-project-id/your-image-name:latest']

  # Step 3: Deploy Cloud Function
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'your-cloud-function-name', '--runtime', 'nodejs16', '--trigger-http']
    dir: 'function'  # Change this to the actual path of your Node.js project
